@Library('jenkins-pipeline')_
import com.cleverbuilder.GlobalVars

pipeline {
    
    agent any
    
    parameters {
        string(name: 'email', defaultValue: 'miguel.anguita@gft.com', description: 'Direcciones de correo para las alertas')

        booleanParam(name: 'Sonar', defaultValue: true, description: 'Se debe ejecutar Sonar.')
        
        booleanParam(name: 'Nexus', defaultValue: true, description: 'El artefacto debe subir a Nexus.')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
    }

    set +x
    info() {
      echo "\033[1;33m[Info]    \033[0m $1"
    }

    error() {
      echo "\033[1;31m[Error]   \033[0m $1"
    }


    success() {
      echo "\033[1;32m[Success] \033[0m $1"
    }
    
    stages {
        stage('Demo') {
            steps {
                ansiColor('xterm') {
                    info 'Hello World'
                }

                sayHello 'Dave'
          
                sayHello GlobalVars.foo
            }
        }
        
        stage("SonarQuBe Analysis") {
            steps {
                script {
                    if (sonar.toBoolean()) {
                        echo ' =========== ^^^^^^^^^^^^ Pasando Sonar...'
                    } else {
                        echo ' =========== ^^^^^^^^^^^^ Pasando del Sonar...'
                    }
                }
            }
        }
          
        stage("Uploading to Nexus") {
            steps {
                script {
                    if (Nexus.toBoolean()) {
                        echo ' =========== ^^^^^^^^^^^^ Subiendo a Nexus...'
                    } else {
                        echo ' =========== ^^^^^^^^^^^^ Pasando de subir a Nexus...'    
                    }
                }     
            }
        }  
    }
    post {
        always {
            info 'One way or another, I have finished'
            deleteDir() /* clean up our workspace */
        }
        success {
            success 'I succeeeded!'
            echo 'Enviando email a: ' + email
        }
        unstable {
            info 'I am unstable :/'
        }
        failure {
            error 'I failed :('
            info 'Enviando email a: ' + email
            //mail to: 'miguel.anguita@gft.com',
                //subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                //body: "Something is wrong with ${env.BUILD_URL}"
        }
        changed {
            info 'Things were different before...'
        }
    }
}
