@Library('jenkins-pipeline')_
import com.cleverbuilder.GlobalVars

pipeline {
    
    agent any

    options {
          ansiColor('xterm')
    }

    parameters {
        string(name: 'email', defaultValue: 'miguel.anguita@gft.com', description: 'Direcciones de correo para las alertas')

        booleanParam(name: 'Sonar', defaultValue: true, description: 'Se debe ejecutar Sonar.')
        
        booleanParam(name: 'Nexus', defaultValue: true, description: 'El artefacto debe subir a Nexus.')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
    }
    
    stages {
        stage('Demo') {
            steps {

                echo 'Hello World'

                sayHello 'Dave'
          
                sayHello GlobalVars.foo
            }
        }
        
        stage("SonarQuBe Analysis") {
            steps {
                script {
                    if (sonar.toBoolean()) {
                        echo ' =========== ^^^^^^^^^^^^ Pasando Sonar...'
                    } else {
                        echo ' =========== ^^^^^^^^^^^^ Pasando del Sonar...'
                    }
                }
            }
        }
          
        stage("Uploading to Nexus") {
            steps {
                script {
                    if (Nexus.toBoolean()) {
                        echo ' =========== ^^^^^^^^^^^^ Subiendo a Nexus...'
                    } else {
                        echo ' =========== ^^^^^^^^^^^^ Pasando de subir a Nexus...'    
                    }
                }     
            }
        }  
    }
    post {
        always {
            ansiColor('xterm') {
                echo '\033[34m [INFO] One way or another, I have finished \033[0m'
            }
            deleteDir() /* clean up our workspace */
        }
        success {
            ansiColor('xterm') {
                echo "\033[32m [SUCCESS] I succeeeded! \033[0m"
                echo '\033[34m Enviando email a: \033[0m ' + email
            }
        }
        unstable {
            ansiColor('xterm') {
                echo "\033[33m [WARNING] I am unstable :/ \033[0m"
            }
        }
        failure {
            ansiColor('xterm') {
                echo "\033[31m [ERROR] I failed :( \033[0m"
                echo '\033[34m Enviando email a: \033[0m ' + email
            }
            //mail to: 'miguel.anguita@gft.com',
                //subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                //body: "Something is wrong with ${env.BUILD_URL}"
        }
        changed {
            ansiColor('xterm') {
              echo "\033[33m [WARNING] Things were different before... \033[0m"
            }
        }
    }
}


//ansiColor('xterm') {
//    echo "\033[31m [ERROR] \033[0m"
//    echo "\033[32m [SUCCESS] \033[0m"
//    echo "\033[33m [WARNING] \033[0m"
//    echo "\033[34m [INFO] \033[0m"
//}






